### ISSUE TITLE
verify converting to_a does not raise an error

### ISSUE THREAD

**Issue by pcai** [pcai/safe_query#1]
The tests at https://github.com/pcai/safe_query/blob/main/spec/activerecord/safe_query_spec.rb are missing a case mentioned in the docs

Namely, a potentially unsafe query that would normally raise an exception can be avoided by converting the relation to an array first.

This case should be explicitly tested in the specs

**Comment by franlocus** [comment]
Hi! I'd like to work on this.
Interesting gem btw, congrats.

**Comment by pcai** [comment]
ok @franlocus let's do this

**Comment by franlocus** [comment]
> ok @franlocus let's do this

Done! Let me know if it's OK :smile:

**Comment by pcai** [comment]
Thanks, this looks good so I merged it. If you came from BB you may need to contact me separately as I can't find anything on that platform to formally assign it to you

**Comment by franlocus** [comment]
Awesome, these kinds of experiences are highly appreciated by beginners! Thanks for letting me contribute Peter.
Yes, at the moment, there is no option on BB. I'll reach out to you separately :smiley:
